version: "3.7"

services:
  quirrel:
    image: docker.pkg.github.com/quirrel-dev/quirrel/quirrel
    environment:
      PASSPHRASES: "${QUIRREL_PASSPHRASE}"
      REDIS_URL: redis://redis
    ports:
      - 4000:3000
  redis:
    image: redis
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOST=redis
    ports:
      - 8081:8081
